Add player features
TimeLineAnnotator/desktop pull request #132
Opened 2024-06-08 19:32 UTC by azfoo

closes #123.

2024-06-08 19:34 UTC, azfoo commented
mostly done, except for adding icons to the loop and volume toggle - will do so in the coming week.
would also like to add another button to reset the playback speed to 1.0x, if you don't think that is too much clutter.

2024-06-09 13:11 UTC, FelipeDefensor requested changes
Volume, playback control and looping seem to be functional. Great job! There's some work to be done on the UI and the code design of the loop implementation, see my comments.

I'm getting two test failures: `TestHierarchyTimelineComponentManager.test_merge_two_units_with_unit_with_children_in_between` and `TestSplit.test_split_unit_with_children`.

Also, If we loop a hierarchy, play it and then drag its start, we can get it to be after the current play point. I think it is weird for the playback to be outside the loop at any time, if the loop if active. I think this is minor though, and if it proves hard to fix we can add it to the backlog.

2024-06-09 13:11 UTC, FelipeDefensor commented on tilia/ui/timelines/hierarchy/element.py
> +
I agree that the looped element should highlighted, good call. However, I think the highlight is too inconspicuous, as it is. Also, the _looped_ area should be highlighted. Audacity gives us a perfect example:

![image](https://github.com/TimeLineAnnotator/desktop/assets/87732202/55192e23-b5ba-4862-ae7d-1e23b97ad64a)

If we do that across timelines, users can scroll vertically without losing sight of it. Additionally, that kind of highlight is something users have grown to expect if they are familiarized with DAWs or video editors. To draw something on all timelines you could mimick what is done for the playback line (see `TimelineUis.set_playback_line_position`, for instance).

2024-06-09 13:20 UTC, FelipeDefensor commented
It's worth noting that playback rate control _and_ looping YouTube streams (without downloading them) is something that no other software offers. This combo is very useful for transcription.

2024-06-10 16:02 UTC, azfoo commented on tilia/media/player/youtube.html
> +              'onError': onError,
There is one case in which the error doesn't make sense that probably has to do with the way regex matches. 
YouTube URLs look like `https://www.youtube.com/watch?v=[video_id]` and `https://www.youtube.com/watch?v=[video_id&ab_channel=[channel_name]`. The first passes the right id but the second doesn't. The error thrown then says that the id is incorrect but I suspect it is because the channel name gets passed in too.

2024-06-10 16:06 UTC, azfoo commented on tilia/ui/player.py
> +        self.play_toggle_action.blockSignals(False)
It makes sure that the play toggle is switched back to play after stopped is clicked. I suppose it could be substituted with the more general `on_ui_update_silent` instead.

2024-06-10 16:10 UTC, azfoo commented on tilia/media/player/base.py
> +        post(Post.PLAYER_UI_UPDATE, PlayerToolbarElement.TOGGLE_LOOP, True)
The reason for it being here is that taking it outside of the individual timelines makes it possible to set a loop that works across multiple hierarchy timelines. Generalising it like that allows for more flexibility and reduces the potential for strange behaviour if someone selects hierarchies from different timelines.

2024-06-10 16:12 UTC, azfoo commented on tilia/ui/player.py
> +                self.pr_spinbox_update_silent()
playback_rate. I didn't know if spelling it out would make the name too long, but thought it might be sufficiently obvious what it was for from the rest of the code. Do you think we should give it a different name?

2024-06-10 16:12 UTC, azfoo commented on tilia/ui/timelines/hierarchy/element.py
> +
Should we leave the individual components highlighted if we highlight the entire section too?

2024-06-10 19:27 UTC, azfoo commented on tilia/ui/player.py
> +        self.volume_slider = QSlider(Qt.Orientation.Horizontal)
Any suggestions on colour?

2024-06-10 23:03 UTC, azfoo commented on tilia/ui/timelines/hierarchy/element.py
> +
Again, any ideas on colour? 

I've also made the slider coloured because there will not be any feedback if there aren't any other timelines.

2024-06-17 15:44 UTC, FelipeDefensor requested changes
Loopbox looks great. I would prefer pure gary without the orange, though.

Aside some minor UI matters I mentioned, the bulk of what's still to be done is the design improvements I mentioned in the last review.

2024-06-17 15:44 UTC, FelipeDefensor commented on tilia/ui/player.py
> +        self.addWidget(self.toolbar_stack)
I'm not sure about this, but I'm willing to go for this if you feel reasonably secure about it. I feel the text just looks alien and kind of ugly up there where the controls should be. Maybe that's just habit speaking, though.

2024-06-17 15:44 UTC, FelipeDefensor commented on tilia/ui/timelines/collection/collection.py
> +    def on_timeline_component_deleted(self, _: TlKind, tl_id: int, component_id: int, __: bool):
What argument are we ignoring here?

2024-06-17 15:44 UTC, FelipeDefensor commented on tilia/ui/timelines/hierarchy/element.py
> +
Now that we have the looped area highlighted, this looks redundant. Also, the straightness of the area highlight kind of clashes with the fuzziness of the blur, to my eyes. What do you think?

2024-06-17 15:44 UTC, FelipeDefensor commented on tilia/media/player/base.py
> +        post(Post.PLAYER_UI_UPDATE, PlayerToolbarElement.TOGGLE_LOOP, True)
That motivation is pertinent, but the solution is to the use `TimelineUIs` class. See how the `Post.HIERARCHY_SELECTED` and `Post.HIERARCHY_DESELECTED` request are handled there, for instance.

2024-06-17 15:46 UTC, FelipeDefensor commented
I think some comments got duplicated from the last review.

2024-06-17 16:30 UTC, azfoo commented on tilia/media/player/youtube.html
> +              'onError': onError,
It isn't technically outdated. YouTube keeps coming up with new ways to display links so it's an ongoing issue of trying to regex the id out of the link. No solution will be perfect.

2024-06-17 16:31 UTC, azfoo commented on tilia/ui/player.py
> +        self.volume_slider = QSlider(Qt.Orientation.Horizontal)
will do.

2024-06-17 16:31 UTC, azfoo commented on tilia/ui/player.py
> +                self.pr_spinbox_update_silent()
will do.

2024-06-17 16:32 UTC, azfoo commented on tilia/ui/player.py
> +    def on_ui_update_silent(self, element_to_set, value):
no, it is for updating individual components in the player toolbar without triggering it

2024-06-17 16:33 UTC, azfoo commented on tilia/timelines/base/timeline.py
> +    def delete_component(self, component: TC, loop_remove = True) -> None:
probably. will try.

2024-06-17 16:38 UTC, azfoo commented on tilia/ui/timelines/collection/collection.py
> +    def on_timeline_component_deleted(self, _: TlKind, tl_id: int, component_id: int, __: bool):
the loop flag that will be removed

2024-06-17 16:40 UTC, azfoo commented on tilia/ui/timelines/hierarchy/element.py
> +
I think knowing which components are setting the loop is nice. Not sure myself about showing it this way. 
We could do without the feedback, or come up with a different solution. What do you think?

2024-06-17 17:12 UTC, azfoo commented on tilia/ui/timelines/hierarchy/element.py
> +
I'm thinking of moving all colours to settings, since the new window makes things easy to see colours live and pick them. That would reduce the chances of tinting something to a colour that cannot be seen against the original colour. But we could go with that grey for a start.

2024-06-17 18:39 UTC, FelipeDefensor commented on tilia/ui/timelines/hierarchy/element.py
> +
What displaying the loop icon on top of the components?

2024-06-17 18:40 UTC, FelipeDefensor commented on tilia/ui/player.py
> +        self.addWidget(self.toolbar_stack)
Ok. Feel free to solve this to your best judgment.

2024-07-01 16:38 UTC, FelipeDefensor requested changes
Overall, looks very good! Especially good job on refactoring the code out of the player module. I think we have all the major issues solved. A few necessary tasks before merging:

- Add tests for looping logic
- Differentiate slider timeline line and loop shade somewhow (see image below). We could change colors or add an outline to the slider line.
- Improve loop icon legibility (see image below). I think the font is too small, and so the curves looks jagged, at least in my computer. Couldn't we use the same icon as the toolbar?
- Consider using black as volume slider trough color. That may look  more consistent with the other toolbar elements. Your call, ultimately.

![image](https://github.com/TimeLineAnnotator/desktop/assets/87732202/b4f52ff8-cc6a-4a0c-ba42-88ac7d60c57f)

2024-07-04 16:02 UTC, FelipeDefensor approved these changes
I think we're done here, great job! Feel free to (squash and) merge.

On a side note: How much do you really like that blur effect around the slider line? As I said wrt the previous loop highlight, I think it clashes with the clear edges of the rest of the app. I would like to change that, in the future.

2024-07-04 16:06 UTC, azfoo commented on tests/ui/timelines/test_timelineui_collection.py
> +        tilia_state.duration = 100
I know - wondered about keeping that line in because tests should show explicitly how the app functions. Happy to remove it though.

2024-07-04 16:08 UTC, azfoo commented
> On a side note: How much do you really like that blur effect around the slider line? As I said wrt the previous loop highlight, I think it clashes with the clear edges of the rest of the app. I would like to change that, in the future.

Mostly because there isn't a way of adding an outline to a line item, so this was a hacky way around it. At some future point, qGraphicsLineItem could be subclassed and reimplemented with an actual outline.

2024-07-04 16:28 UTC, FelipeDefensor commented on tests/ui/timelines/test_timelineui_collection.py
> +        tilia_state.duration = 100
Yeah, explicit is better here, I agree. Let's leave this as is.

2024-07-04 16:30 UTC, FelipeDefensor commented
> > On a side note: How much do you really like that blur effect around the slider line? As I said wrt the previous loop highlight, I think it clashes with the clear edges of the rest of the app. I would like to change that, in the future.
> 
> Mostly because there isn't a way of adding an outline to a line item, so this was a hacky way around it. At some future point, qGraphicsLineItem could be subclassed and reimplemented with an actual outline.

Yes, we could use that class in other places. I think the easiest way to do it is to have a slighthly bigger line behind the actual one with the color of the outline. Let's worry about that later, though.

2024-07-04 16:54 UTC, merged