reopening windows
TimeLineAnnotator/desktop pull request #152
Opened 2024-07-04 13:45 UTC by azfoo

closes #148, #151
make pdf, video and youtube windows reopenable

2024-07-04 14:03 UTC, FelipeDefensor requested changes
Nice! Let's abstract the window functionality into a mixin (see coment) and I think we are good to go.

2024-07-04 14:03 UTC, FelipeDefensor commented on tilia/ui/timelines/pdf/timeline.py
> +            self.show()
This code is shared by the three windows classes, right? Let's make a mixin class and inherit from that instead of duplicating the code in each class (see the `CursoMixIn` class in case you're not familiar with the pattern).

2024-07-04 15:15 UTC, azfoo commented on tilia/ui/timelines/pdf/timeline.py
> +            self.show()
fixed now

2024-07-04 16:15 UTC, FelipeDefensor commented
The abstraction is perfect.

Found this bug: reopening the video window with a local media loaded results in a blank window.

https://github.com/TimeLineAnnotator/desktop/assets/87732202/7c64d169-d614-4cb5-940e-955619a44930

2024-07-04 16:17 UTC, FelipeDefensor commented
> The abstraction is perfect.
> 
> Found this bug: reopening the video window with a local media loaded results in a blank window.
> blank-reopened-video-window.mp4

Doesn't happen with YouTube player.

2024-07-04 16:25 UTC, FelipeDefensor requested changes
See comments and the bug I found.

2024-07-04 16:25 UTC, FelipeDefensor commented on tilia/media/player/qtvideo.py
> +        super().__init__("TiLiA Player")
![image](https://github.com/TimeLineAnnotator/desktop/assets/87732202/d8f09178-1f83-4e4a-9d4f-288a8be1abaa)

Having the "TiLiA" before the "actual name" of the window looks very strange because it is redundant (we're already inside TiLiA) but I imagine the rationale is that this name will be also displayed by the OS window manager. I think we should pass two different strings to the constructor to solve this.

2024-07-04 16:25 UTC, FelipeDefensor commented on tilia/media/player/qtvideo.py
> +        super().__init__("TiLiA Player")
Also, the menu string should make it explicit that this is the video player, not to be confused with the "player" "embedded" in the toolbar/slider timeline.

2024-07-12 16:01 UTC, FelipeDefensor commented
Oh, I missed the review request, sorry! I will review later today.

2024-07-12 18:57 UTC, FelipeDefensor approved these changes
The refactor looks good and everything works now. Feel free to squash and merge.

2024-07-12 19:23 UTC, merged