update csv import for beat
TimeLineAnnotator/desktop pull request #175
Opened 2024-07-17 02:55 UTC by azfoo

measure_number column:
- input number in column if measure number change is required. subsequent bars will count up from given number. will also cause ui to force display specified measure's number.

is_first_in_measure column:
- input `True` if given time is first beat of measure.

2024-07-17 11:21 UTC, FelipeDefensor requested changes
I like the solution. We really need some tests here as importing from CSV has proved to be error prone.

2024-07-17 11:21 UTC, FelipeDefensor commented on tilia/parsers/csv/beat.py
> +            beats_per_measure = (
`beat_pattern` is a `list[int]` but it seems like you are treating it as an `int` in line 80. The idea of it being a list is to enable the user to set it to cycles like `4,3,3`.

2024-07-17 11:24 UTC, FelipeDefensor commented on tilia/parsers/csv/beat.py
> +            beats_per_measure = (
Now I can see that it duplicates information, since the `is_first_in_measure` beat property already enables us to get that. That duplication leads to unnecessary complexity sometimes and maybe that is the case here. I would not oppose a refactor to eliminate the duplication in the future.

2024-07-19 22:07 UTC, azfoo commented
updated! now with tests and I also fixed the confusing list/0 variable.

2024-07-20 14:03 UTC, FelipeDefensor approved these changes
Nice solution. I'm fine with this the way it is, but make sure to consider my comments.

2024-07-20 14:03 UTC, FelipeDefensor commented on tests/parsers/csv/test_beats_from_csv.py
> +
Perhaps it would be nice to test the case where there is a `is_first_in_measure` column but there are no values in it. Also, what happens if the user inserts invalid values in that column?

2024-07-25 00:04 UTC, azfoo commented on tests/parsers/csv/test_beats_from_csv.py
> +    data = "time,measure_number\n5,\n10,\n15,\n20,\n25,\n30,8"
There isn't really a need for the line break because it's the last line. 30 is the time and 8 is the measure number.

2024-07-25 11:04 UTC, FelipeDefensor commented on tests/parsers/csv/test_beats_from_csv.py
> +    data = "time,measure_number\n5,\n10,\n15,\n20,\n25,\n30,8"
Wow, that was really silly of me 😅

2024-07-25 11:52 UTC, FelipeDefensor approved these changes
All the problems I had with importing the Huapstimme data seem to be fixed. I think you're done here 😃.

2024-07-25 11:52 UTC, FelipeDefensor commented on tilia/parsers/csv/beat.py
> +                    and str(row[params_to_indices["is_first_in_measure"]]).lower()
Do we need `str` here? I thought the csv reader parsed everything into strings.

2024-07-26 01:58 UTC, azfoo commented on tilia/parsers/csv/beat.py
> +                    and str(row[params_to_indices["is_first_in_measure"]]).lower()
good point.

2024-07-26 02:08 UTC, merged