Add relative times
TimeLineAnnotator/desktop pull request #180
Opened 2024-07-19 20:48 UTC by azfoo

closes #178

2024-07-20 13:32 UTC, FelipeDefensor requested changes
As always, overall this looks great. I have yet to test things more thoroughly, but everything seems to be working.I made minor code style comments, mostly.

There is only one relevant design issue to discuss. I'm not sure about hiding the components if changing the effective boundaries gets them out of bounds. I can't see a use case where the user would find out-of-bounds, invisible components useful, and I imagine that making them invisible might make the user forget to edit them, and potentially leave them outdated. Also, it adds complexity on our side, having to deal with those `time is None` cases. What do you think about prompting the user and deleting the out-of-bounds elements, instead?

2024-07-20 13:32 UTC, FelipeDefensor commented on tilia/errors.py
> +    "Seeked time ({}) is outside of current time ({} - {}). Edit current start and end times in metadata to seek to this point.",
I think the more user-friendly term here is "selected time". The second use of seek is fine, by me, as what came before makes it clear to what we are referring, evne if the user doesn't know the mor etechnical term for what he is doing.

2024-07-20 13:32 UTC, FelipeDefensor commented on tilia/media/player/base.py
> +class Time:
Also, this would be a good place for using dataclasses, in case you have heard of them. No need to change it, though.

2024-07-20 13:32 UTC, FelipeDefensor commented on tilia/ui/coords.py
> +            or time > get(Get.MEDIA_DURATION) + relative_time.start
Again, chained comparisons would help to make this a bit more readable.

2024-07-20 13:32 UTC, FelipeDefensor commented on tilia/ui/timelines/harmony/elements/harmony.py
> +        if x == None:
Minor thing: The recommended way to compare with `None` is through the `is` operator, as in `if x is None`. We should check for identity, and not equality, as `None` is a singleton in Python (https://stackoverflow.com/a/25317251/15862653).

2024-07-20 13:32 UTC, FelipeDefensor commented on tilia/ui/timelines/hierarchy/element.py
> +        if self.start_x != None and self.end_x != None:
As there are multiple comparisons with None, I recommend changing them all according to the comment above.

2024-07-20 13:32 UTC, FelipeDefensor commented on tilia/ui/windows/metadata.py
> +    def populate_with_media_times(self):
Do you think it would be nice to also display the absolute media length? I think it might m be useful if the user wants to reset the effective end to the absolute length.

2024-07-20 13:35 UTC, azfoo commented on tilia/media/player/base.py
> +            if time < self.relative_time.start or time > self.relative_time.end:
sorry, I forgot how to python 😅

2024-07-20 13:39 UTC, FelipeDefensor commented
Actually, you can't used chained comparisons there as the operator is an `or`. Apparently you still remember you Python :))

2024-07-20 13:41 UTC, azfoo commented on tilia/ui/windows/metadata.py
> +    def populate_with_media_times(self):
The main reason why I went with hiding is that AudiowaveTimeline reads the entire file and displays components for everything - that's something that can be changed in the timeline I guess. The other use case I was thinking of was for showing specific parts of the file and hiding the rest. (I'm hoping YouTube will update their API soon to include chapters and all the fun things you can do with that).

But happy to not have the None - perhaps a tuple to show whether it is out-of-bounds?

2024-07-20 13:43 UTC, azfoo commented on tilia/ui/windows/metadata.py
> +    def populate_with_media_times(self):
sound. will do.

2024-07-20 13:49 UTC, azfoo commented
The main reason for hiding is in the AudiowaveTimeline because that displays components for the entire file - easily changeable, so we could go without the None. 
_scale_or_crop clears up all the other timelines anyway so I think we could technically do without the checks in the other timelines. 
Alternatively, I was thinking get_x_by_time could return a tuple (value, whether it is out of bounds) so we don't have mixed datatypes.

2024-07-20 14:12 UTC, FelipeDefensor commented
> The main reason for hiding is in the AudiowaveTimeline because that displays components for the entire file - easily changeable, so we could go without the None. _scale_or_crop clears up all the other timelines anyway so I think we could technically do without the checks in the other timelines. Alternatively, I was thinking get_x_by_time could return a tuple (value, whether it is out of bounds) so we don't have mixed datatypes.

Ok. So you are saying that we could use the `_scale_or_crop` to delete the out-of-bounds elements? If so, great. I like not having mixed types and I am a fan of returning tuples with bool flags to indicate success and the like, you will see those all around the codebase, so I think that is the way to go if we are going with the inbound check. I still prefer avoiding the complexity in this case if we can, though.

2024-07-22 12:26 UTC, FelipeDefensor commented
Hi, Anne. I have found some bugs.

---
Initial hierarchy is not visible when creating hierarhcy timeline after setting effective boundary != 0.

Steps to reproduce:
- New file
- Load media
- Set effective start != 0
- Create hierarchy timeline
---
Effective times are not being loaded from saved file.

Steps to reproduce:
- New file
- Load media
- Set effective start != 0
- Set effective end != media length
- Save file
- Open same file

Result: Effective start is set to 0 and effective end is set to media length.
---
Creating new file after setting effective start has wrong time displayed

Steps to reproduce:
- New file
- Load media
- Set effective start to 10
- Create new file with File > New file

Result: Displayed time is 59:50.0/59:50.0

2024-07-26 02:17 UTC, azfoo commented
not quite fixed. I'm slightly stuck on how to serve get.media_metadata in the failing tests. could you help?

2024-07-26 12:58 UTC, FelipeDefensor commented
> not quite fixed. I'm slightly stuck on how to serve get.media_metadata in the failing tests. could you help?

Sure! I will take at a look at this shortly.

2024-07-26 14:52 UTC, FelipeDefensor commented
> > not quite fixed. I'm slightly stuck on how to serve get.media_metadata in the failing tests. could you help?
> 
> Sure! I will take at a look at this shortly.

The problem is that due to how I implemented the test teardown, at the moment `tilia_state` tries to reset the duration to the default 100, `file_manager` has already been torn down, and, with that, has stop serving `Get.MEDIA_METADATA`. However, resetting the duration to 100 involves calling `App.set_media_duration` which posts `Post.FILE_MEDIA_DURATION_CHANGED` which triggers `Player.on_media_duration_available`. That last method tries to get `Get.MEDIA_METADATA`, but that's not available because, as said above, the file manager has already been torn down.

I'm not sure how to fix this yet, but couldn't we just store the relative times in the player itself and evade the need to ask the file manager for them? Actually, don't we already do that in `Player.relative_time`?

2024-07-27 19:20 UTC, azfoo commented
That should fix everything

2024-07-30 18:17 UTC, FelipeDefensor requested changes
I think the bugs have all been solved, but this has a lot of moving parts. See my comments.

I also want to discuss the "relative times" name. I'm not sure what they would be relative too. "Absolute time" does, on the other hand, sound like a good name for the "file" boundaries. As alternatives to "relative start/end", we have "playback start/end", "annotation start/end" and "timelines start/end". We could also go with setting "start offset" and "end offset" instead, but that would require adaoting some of the code. What are your thoughts on this?

2024-07-30 18:17 UTC, FelipeDefensor commented on tilia/timelines/collection/collection.py
> +    def _scale_or_crop_timelines(self):
I think this function has too many responsabilities. Sorry for suggesting that we reuse it in this context. Asking if a user wants to rescale the timelines doesn't really make sense when changing the effective boundaries. As the absolute size of the media hasn't changed, I can't see any reason for wanting to scale the components, as they were surely made accodirng to the appropriate (and only) scale in the first place.

Asking if the user wants to crop makes sense though, as component that were in bounds might get out of bounds if we change the effective range.

The more durable solution would probably be to split scaling and cropping logic into separate functions and call both when loading a new media but just the crop part when changing the effective boundaries.

2024-07-30 18:17 UTC, FelipeDefensor commented on tilia/timelines/collection/collection.py
> +    def scale_timeline_components(self, offset: float, factor: float) -> None:
I think I get what the offset does but I can't see a use case. I'm doubly sorry for not commenting on the scaling before, as that would have maybe saved you the trouble of adding this.

I may be mistaken about removing the scale option when changing effective boundaries, though. Please do say if you think this is a useful feature. I would rather be wrong in this case, actually.

2024-07-30 18:29 UTC, azfoo commented
> I also want to discuss the "relative times" name. I'm not sure what they would be relative too. "Absolute time" does, on the other hand, sound like a good name for the "file" boundaries. As alternatives to "relative start/end", we have "playback start/end", "annotation start/end" and "timelines start/end". We could also go with setting "start offset" and "end offset" instead, but that would require adaoting some of the code. What are your thoughts on this?
>
I like playback start/end best. Naming it offset would mean more maths (which isn't too bad) but it is a strange way of thinking about time - also that it would involve checks to make sure the boundaries don't overlap.

2024-07-30 18:35 UTC, azfoo commented on tilia/timelines/collection/collection.py
> +    def scale_timeline_components(self, offset: float, factor: float) -> None:
I think scale could potentially be useful in the context of the user trying to compare two different media sources and seeing how they line up with each other - eg. if the rate of change in tempo is consistent, not the actual tempo - and creating comparative charts from there. 
Another strange use could be if the user found a more accurate remaster of an old warbly recording that is less warbly and re-recorded at the right rpm - in that case, the time ratio between elements will remain the same.

2024-07-30 19:27 UTC, azfoo commented on tilia/timelines/collection/collection.py
> +    def scale_timeline_components(self, offset: float, factor: float) -> None:
offset is the c of y = mx + c - it corrects the start time in case it is non 0.

2024-07-30 19:46 UTC, FelipeDefensor commented on tilia/timelines/collection/collection.py
> +    def scale_timeline_components(self, offset: float, factor: float) -> None:
> I think scale could potentially be useful in the context of the user trying to compare two different media sources and seeing how they line up with each other - eg. if the rate of change in tempo is consistent, not the actual tempo - and creating comparative charts from there. Another strange use could be if the user found a more accurate remaster of an old warbly recording that is less warbly and re-recorded at the right rpm - in that case, the time ratio between elements will remain the same.

I agree, but in both cases they would be loading a new media and not changing the playback start/end of the current one, right? I'm not suggesting that we remove scaling, but that we only prompt for that when loading new media.

2024-07-30 19:51 UTC, azfoo commented on tilia/timelines/collection/collection.py
> +    def scale_timeline_components(self, offset: float, factor: float) -> None:
I see what you mean - but if the new file were not previously cropped exactly to where things should start and end, there wouldn't be a way for the app to crop it internally and scale. (Am I still misunderstanding something?😅)

2024-07-30 20:00 UTC, FelipeDefensor commented
> > I also want to discuss the "relative times" name. I'm not sure what they would be relative too. "Absolute time" does, on the other hand, sound like a good name for the "file" boundaries. As alternatives to "relative start/end", we have "playback start/end", "annotation start/end" and "timelines start/end". We could also go with setting "start offset" and "end offset" instead, but that would require adaoting some of the code. What are your thoughts on this?
> 
> I like playback start/end best. Naming it offset would mean more maths (which isn't too bad) but it is a strange way of thinking about time - also that it would involve checks to make sure the boundaries don't overlap.

Ok, I like playback start/end too. Let's go with that.

2024-07-31 11:34 UTC, FelipeDefensor commented on tilia/timelines/collection/collection.py
> +    def scale_timeline_components(self, offset: float, factor: float) -> None:
Oh, you mean in the case we are loading a file to a analysis that already has playback start != 0 and/or playback end != media length?

If that's the case, I have to say I hadn't thought about it. How are you planning on dealing with that?

If that's not the case, then I'm being a little slow to understand what you're saying and will have to ask you to explain it again 😅.

2024-08-07 19:41 UTC, FelipeDefensor commented on tilia/timelines/collection/collection.py
> +    def scale_timeline_components(self, offset: float, factor: float) -> None:
Oh, now I get it! This does seem useful, so let's keep the scaling option. I think we should improve the confirmation dialog, then, I believe the current one may come as a surprise to a user that is only looking to change the playback start/end. How about something like this?

![image](https://github.com/user-attachments/assets/763a48dc-1736-4025-b944-e7cd3699365b)

2024-08-07 19:54 UTC, azfoo commented on tilia/timelines/collection/collection.py
> +    def scale_timeline_components(self, offset: float, factor: float) -> None:
Are you implying the current separate scale/crop dialogues get squished into one? That seems much more reasonable than asking twice, although the dialogues for a longer/shorter new time will have to be different.

I had plans for building the RangeSlider (implemented in QML but not ported over to PyQt) - which will be nice for sliding both start and end points in setting times in metadata and here. But that will be a plan for much later because it looks to be potentially complicated.

2024-08-07 20:41 UTC, FelipeDefensor commented on tilia/timelines/collection/collection.py
> +    def scale_timeline_components(self, offset: float, factor: float) -> None:
I forgot they were separate, so yes, that's what I suggest. Which one of the two I sent gets displayed depends on if the new time is longer or shorter, like you said.

A RangeSlider would definitely help, but we can certainly wait.

2024-08-15 14:32 UTC, FelipeDefensor requested changes
## New dialog
I really like the dialog! It's much clearer than the previous one. 

## Bugs
Given the complexity that this feature adds, it's no surprise that I found a few bugs:

- Hierarchy positions are not being updated after increasing duration and choosing the "fill with empty space" option
- Decreasing duration and compressing timelines twice in a row break hierarchy timelines
- Decreasing end time and cropping followed by increasing start and cropping break hierarchy timelines (see video below)




https://github.com/user-attachments/assets/6a9ea434-816a-4155-acba-9821f5425127


## PR process
The size of the code that GitHub prompts me to review has gotten out of hand on this PR. If I understand correctly, you have done something that rewrote the git's history and had to do a `git push --force` after the last review. Doing that makes so that all the PR's commits will be marked for review on the next review request. I think the ideal thing would be to defer anything that rewrites git's history to after the PR has been approved and right before merging it. Can we do that?

2024-08-15 14:32 UTC, FelipeDefensor commented on tilia/ui/timelines/audiowave/element.py
> +        self.selected = False
This makes so that every time we redraw (e.g. when zooming) the component gets deselected. It should go back to the initializer. The rest is fine.

2024-08-15 14:56 UTC, FelipeDefensor commented
I changed the PR destination to the v0.5 branch. As we didn't get this done before starting the manual testing, I think it's safer to postpone the release. We can still use relative times in the proofs-of-concept for the article by setting them directly on the `.tla`. I will have to check if it will be possible to open them (after downloading from the website) on the v0.4.1 desktop app, though.

2024-08-31 21:15 UTC, azfoo commented
> > Regarding PR process, most of the rewrites happen because of rebasing to upstream. Would you prefer if I didn't rebase until everything is finished?
> 
> Let's try that and see if it makes things easier, yes.

My bad, I did it again... It is only the last two commits that are actually updates.

2024-09-04 18:56 UTC, FelipeDefensor commented
> > > Regarding PR process, most of the rewrites happen because of rebasing to upstream. Would you prefer if I didn't rebase until everything is finished?
> > 
> > 
> > Let's try that and see if it makes things easier, yes.
> 
> My bad, I did it again... It is only the last two commits that are actually updates.

No problem, thanks for the warning.

Just to make sure: you're still working on those bugs so I still shouldn't review, right?

2024-09-20 12:20 UTC, azfoo commented
sorry for the delay - bugs have now been resolved

2024-09-24 20:44 UTC, closed without merging