feat: script generator
TimeLineAnnotator/desktop pull request #186
Opened 2024-07-29 22:51 UTC by azfoo

mostly working. 
save is broken - path.parent.exists() fails even though path does exist.
having spaces in directory names is also another cause of failure.

2024-07-30 11:43 UTC, FelipeDefensor reviewed
Nice!

This is a standalone script, right? If so, I think we should host it on a `tilia-utils` repo. An alternative would be to integrate this into the CLI.

Design-wise, I would really like to see `run` broken up in three or four functions for readability. See my comments.

If the idea is to mention this on the article, I think you can go ahead and do that while we polish this and figure out where it should go.

2024-07-30 11:43 UTC, FelipeDefensor commented on import_timelines.py
> +def run():
The six indentations levels make this hard to read. Let's refactor. I will leave some ideas in specific parts below.

2024-07-30 11:43 UTC, FelipeDefensor commented on import_timelines.py
> +            print(f"Multiple media files found in {folder_name}: {media_data}")
We could turn these into guard clauses to avoid the extra indentation level and make clear that these are "error" cases.

2024-07-30 11:43 UTC, FelipeDefensor commented on import_timelines.py
> +                    filenames.remove("set_media_length.txt")
Ideally, there should be no logic in the `open` context manager, just the writing itself. You can compute the strings before entering it.

2024-07-30 11:43 UTC, FelipeDefensor commented on import_timelines.py
> +                            print(e)
This is a good candidate for extraction into a separate function.

2024-07-30 11:43 UTC, FelipeDefensor commented on import_timelines.py
> +                            has_beat |= check_has_beat
Thanks for letting me know about this operator 😃

2024-07-30 11:43 UTC, FelipeDefensor commented on import_timelines.py
> +                        except ReferenceError as e:
Are you sure this is not supposed to a `KeyError` or `ValueError`? `ReferenceError` only happens when using a `WeakRefDict` AFAIK.

2024-07-30 11:43 UTC, FelipeDefensor commented on import_timelines.py
> +                    print(f"{folder_name} requires beat but no beat csv found.")
Another guard clause candidate.

2024-07-30 13:02 UTC, azfoo commented on import_timelines.py
> +def run():
Agreed. Was trying to work out where to take things out...

2024-07-30 13:04 UTC, azfoo commented on import_timelines.py
> +                        except ReferenceError as e:
Realistically, we could name it whatever we want as long as it makes sense to the user. I was having a hard time deciding what kind of error it was. Do you have a preference between Key and Value?

2024-07-30 13:11 UTC, azfoo commented
> This is a standalone script, right? If so, I think we should host it on a `tilia-utils` repo. An alternative would be to integrate this into the CLI.
> 
I wasn't sure where this should live (certainly not where it currently lives). If you think it belongs on a different repo, you'll need to move it because I don't have access to making new repos. 
Putting it on the CLI, on the other hand, would make it easier to access - where if the directory were you thinking?

There's another WIP on automating script execution once they are created - would that be helpful?

> If the idea is to mention this on the article, I think you can go ahead and do that while we polish this and figure out where it should go.
>
I honestly don't know if it should go in, just thought it would be a useful tool to have instead of having to write out multiple scripts.

2024-07-30 16:58 UTC, FelipeDefensor commented on import_timelines.py
> +                        except ReferenceError as e:
Oh, this is an error we raise, ok. I would say we go with ValueError.

2024-07-30 17:10 UTC, FelipeDefensor commented
> I wasn't sure where this should live (certainly not where it currently lives). If you think it belongs on a different repo, you'll need to move it because I don't have access to making new repos. Putting it on the CLI, on the other hand, would make it easier to access - where if the directory were you thinking?

Let's get that permission granted in any case, then. I was thinking we could have a command like `script generate --recurse` if we're going with the CLI, so that would mean refactoring `script.py` into a separate folder and having a `generate.py` inside it. The downside to integrating this into the CLI is that we're going to have to commit to testing and maintaining this (complex) functionality and some adptation to the CLI code would be needed. If you feel like tackling this now, go for it. Otherwise, we can have this as a standalone and integrate it later, when we need it.

> There's another WIP on automating script execution once they are created - would that be helpful?

Yes, I do think it will be helpful once we get into converting large corpora (soon, I hope).
 
> I honestly don't know if it should go in, just thought it would be a useful tool to have instead of having to write out multiple scripts.

Fair enough. I think there's a point where a mention would fit in nicely. I'll let you know.

2024-07-30 17:23 UTC, azfoo commented
> > I wasn't sure where this should live (certainly not where it currently lives). If you think it belongs on a different repo, you'll need to move it because I don't have access to making new repos. Putting it on the CLI, on the other hand, would make it easier to access - where if the directory were you thinking?
> 
> Let's get that permission granted in any case, then. I was thinking we could have a command like `script generate --recurse` if we're going with the CLI, so that would mean refactoring `script.py` into a separate folder and having a `generate.py` inside it. The downside to integrating this into the CLI is that we're going to have to commit to testing and maintaining this (complex) functionality and some adptation to the CLI code would be needed. If you feel like tackling this now, go for it. Otherwise, we can have this as a standalone and integrate it later, when we need it.
> 
The only dependence on TiLiA at the moment is the constants file to get acceptable media types. Bundling this into the app would make overall access easier to manage. Linking it to scripts would make managing the looping easier as well. 
If "tackling this now" refers to the more flexible due date that is not tomorrow, it probably is doable.

2024-07-30 17:28 UTC, FelipeDefensor requested changes
The whole thing is much more readable, thanks! Couple issues with using `vars` and `locals`, only.

2024-07-30 17:28 UTC, FelipeDefensor commented on import_timelines.py
> +        if "is_by_time" in locals():
This is certainly valid Python, and it's nice to know about `locals`, but it's not idiomatic to rely on such introspection (not sure if that's the right term here) when there are reasonable alternatives. More specifically, Python programs don't usually check if variables are defined before using them. They either are defined and everyone is happy or they're not and we get a `ValueError`. You could have an additional `is_by_measure` bool and check if that's true at this point, instead.

2024-07-30 17:28 UTC, FelipeDefensor commented on import_timelines.py
> +        for media_type, values in vars(constants).items()
Other unrelated constants might get added to that file, so it's better to import the formats explicitly here. If you want a more concise import, you could create an `ALL_SUPPORTED_MEDIA_FORMATS` constant in `tilia.media.constants` concatening the existing ones.

2024-07-30 17:28 UTC, FelipeDefensor commented on import_timelines.py
> +        for media_type, values in vars(constants).items()
Maybe this also qualifies as a kind of instrospection that's better to avoid (see comment below).

2024-08-07 20:13 UTC, FelipeDefensor approved these changes
Looks good to me. Nice job on the tests!

2024-08-07 20:43 UTC, merged