Add Playback times
TimeLineAnnotator/desktop pull request #196
Opened 2024-10-10 00:43 UTC by azfoo

#180, closes #178.
WIP:
~~fix CLI dialog~~

2024-10-15 21:41 UTC, azfoo commented
@FelipeDefensor, need a little help on this one: tests.ui.cli.test_load_media
in trying to avoid the dialog popping up on the CLI, I've called Get.WINDOW_STATE and checked for a NoReplyToRequest (because it is only served in QtUI and not the CLI), which works with the actual CLI, but fails on the test. Somewhere in the setup of the test, QtUI is initialised and is replying. Creating a new Get.UI_TYPE also fails because both UIs give conflicting responses. Any ideas on how to solve this?

2024-10-17 11:06 UTC, FelipeDefensor commented
> @FelipeDefensor, need a little help on this one: tests.ui.cli.test_load_media in trying to avoid the dialog popping up on the CLI, I've called Get.WINDOW_STATE and checked for a NoReplyToRequest (because it is only served in QtUI and not the CLI), which works with the actual CLI, but fails on the test. Somewhere in the setup of the test, QtUI is initialised and is replying. Creating a new Get.UI_TYPE also fails because both UIs give conflicting responses. Any ideas on how to solve this?

Will look into it.

2024-10-17 11:18 UTC, FelipeDefensor commented
I wasn't able to replicate the issue. `test.ui.cli.test_load_media` passes just fine here.

In general, to "patch" a dialog interaction, you should use the `tests.mock.Serve` context manager and pass it the desired response. Note that that will usually be a tuple with the "return value" and a boolean indicating wheter the dialog was succesful (that is, if it was not not closed or cancelled).

2024-10-17 11:21 UTC, FelipeDefensor commented
> I wasn't able to replicate the issue. `test.ui.cli.test_load_media` passes just fine here. Edit: I was running only `test.ui.cli.test_load_media.test_load_media`, now I am able to replicate.
> 
> In general, to "patch" a dialog interaction, you should use the `tests.mock.Serve` context manager and pass it the desired response. Note that that will usually be a tuple with the "return value" and a boolean indicating wheter the dialog was succesful (that is, if it was not not closed or cancelled).

2024-10-17 11:32 UTC, FelipeDefensor commented
Ok, so this is entirely on me. Contrary to what you would expect, the `marker_tl` fixture requests the `marker_tlui` fixture that request the `qtui` fixture. This is first-class spaghetti that I need to unravel. 

There were improvements to the tangled fixtures in v0.4.3, but apparently they were'nt enough. I will see if I can provide a permanent solution in the next few days. You can wait for that, or skip those tests with `@pytest.mark.skip` if you want to move on with this PR.

2024-10-17 12:47 UTC, azfoo commented
Marked skip for now. 
Do review if you have time - don't think there's much change in the code apart from the merge/rebase.

2024-10-17 14:05 UTC, FelipeDefensor commented
> There were improvements to the tangled fixtures in v0.4.3, but apparently they were'nt enough. I will see if I can provide a permanent solution in the next few days. You can wait for that, or skip those tests with @pytest.mark.skip if you want to move on with this PR. Let me know.

Easier than I thought, so I already pushed a commit to dev dealing with this.

Will review this PR later today.

2024-10-17 22:02 UTC, FelipeDefensor commented
Anne, sorry for the delay on the review. I was part of a congress today that took longer than I expected. Will review tomorrow, guaranteed.

2024-10-18 13:05 UTC, FelipeDefensor commented on tilia/media/player/base.py
>                  end_time -= self.E
Did not get this. A comment clarifying would probably be nice.

2024-10-18 13:11 UTC, FelipeDefensor commented on tilia/media/player/base.py
> +        return self._end - self._start
Nice job with this one. If we find ourselves using this pattern often, we may want to use `pydantic`, which provides built-in validation for dataclasses.

2024-10-18 13:26 UTC, FelipeDefensor commented on tilia/timelines/base/timeline.py
> +        self.component_manager.scale(factor, offset_old, offset_new)
I'm not sure I get whats going on here. Could you add a docstring explaining what the offsets do?

2024-10-18 13:28 UTC, FelipeDefensor commented on tilia/timelines/beat/timeline.py
> +            )
We should abstract this into PointTimelineComponent when those commits meet.

2024-10-18 13:31 UTC, FelipeDefensor commented on tilia/timelines/hierarchy/timeline.py
> +            or start < playback_time.start
The `end > start` is handled below, so we should only check if `start < playback_time.start or end > playback_time.end`.

2024-10-18 13:33 UTC, FelipeDefensor commented on tilia/timelines/hierarchy/timeline.py
> +        elif playback_time.end == 0 and (end > media_duration or start < 0):
What is this checking for that is not handled by the previous cases? A comment would be nice.

2024-10-18 13:42 UTC, FelipeDefensor commented on tilia/timelines/hierarchy/timeline.py
> +                self.post_component_event(Post.HIERARCHY_POSITION_CHANGED, hrc.id)
We should not have to manually notify about changes to a component's attributes. This was already wrong in my previous code. Actually, `Post.HIERARCHY_POSITION_CHANGED` does nothing, as no one is listening for it. That and dot-assingning component's attributes should raise eyebrows.

What we should do is use `self.set_component_data` which posts the correct events after doing the assignment.

2024-10-18 13:52 UTC, FelipeDefensor commented on tilia/ui/timelines/audiowave/timeline.py
>                  start_time = element.get_data("start")
I'm just realizing this is O(n) and given that we tipically have thousands of AmplitudeBars, this is pretty bad. No wonder there's lag when box selecting AmplitudeBars. Let's fix this in another commit ASAP.

2024-10-18 13:57 UTC, FelipeDefensor commented on tilia/ui/timelines/collection/collection.py
> +        self.on_loop_change(self.selected_time, self.selected_time)
Why this?

2024-10-18 14:02 UTC, FelipeDefensor commented on tilia/ui/windows/metadata.py
> +            self.has_times = False
Make this a guard clause to avoid the following long indented block.

2024-10-18 14:03 UTC, FelipeDefensor commented on tilia/ui/windows/metadata.py
> +            self.has_times = True
Move this to the top to be closer to the contasting statement on the guard clause case.

2024-10-18 14:03 UTC, FelipeDefensor commented on tilia/ui/windows/metadata.py
> +            self.end_time.valueChanged.connect(lambda value: on_end_time_changed(value))
Do you think abstracting the duplicated code into a class is worth it in this case?

2024-10-18 14:14 UTC, FelipeDefensor commented on tilia/ui/dialogs/scale_or_crop.py
> +        PROMPT = 2
I'm not opposed to using an enum instead of strings, but:
- This should be a `StrEnum` to increase readability (use `enum.auto()` for the values instead of hard-coding`
- We should use the `enum` everywhere. There are still places where Literal['yes', 'no', 'propmpt'] is being used.
- This should be in a "CLI-friendly" place. There should be no reason for the CLI to use code in the `ui.dialogs` dir.

2024-10-18 14:14 UTC, azfoo commented on tilia/ui/timelines/audiowave/timeline.py
>                  start_time = element.get_data("start")
Quick question: is the list of selected elements always sorted?

2024-10-18 14:15 UTC, FelipeDefensor commented on tilia/app.py
> +        match scale_or_crop:
Can't we just `match self.should_scale_timelines`?

2024-10-18 14:18 UTC, FelipeDefensor commented on tilia/app.py
> +            post(Post.FILE_MEDIA_DURATION_CHANGED, duration, start, end)
Those seem to do different things. Was there anything wrong before?

2024-10-18 14:23 UTC, FelipeDefensor requested changes
The code is pretty clean and everything seems to be working. I tried to be more thorough than normal in the review as experience (or trauma) tells me that media loading bugs tend to be hard to spot.

I will try to write a billion tests for this. In the meantime, there are some minor issues to be adressed.

Good job!

2024-10-18 16:36 UTC, FelipeDefensor commented on tilia/ui/timelines/audiowave/timeline.py
>                  start_time = element.get_data("start")
Yes, always sorted, despite the name `ElementManager._add_to_selected_elements_set`.

2024-10-18 16:53 UTC, FelipeDefensor commented on tilia/ui/dialogs/scale_or_crop.py
> +        PROMPT = 2
I had not realized how you were handling the CLI case in `ScaleOrCrop.select`, sorry for that. Some issues with that:

- I feel like we should avoid cathing `NoReplytoRequest` to branch the code. I always imagined that exception as just a wrapper around `ValuError` that made things more understandable.
- That makes the CLI dependent on `QDialog`, which increases coupling between the CLI and `PyQt`.
- It strikes me as an instance of too many responsabilites for a function, that is, handling user interaction in two types of user interfaces.

Please tell me if you feel differently on those issues.

If you don't mind, I would like to commit a refactor that separates the GUI and CLI dialog.

2024-10-18 19:54 UTC, azfoo commented on tilia/app.py
> +        match scale_or_crop:
I've chosen not to set `self.should_scale_timelines` so that it doesn't need to be unset after this operation is done.

2024-10-18 19:58 UTC, azfoo commented on tilia/app.py
> +            post(Post.FILE_MEDIA_DURATION_CHANGED, duration, start, end)
Not calling the post means the player doesn't get updated. Currently, any changes made to the media duration calls `Post.FILE_MEDIA_DURATION_CHANGED` which gets the player to set up the necessary playback times. Player then calls `Post.PLAYER_DURATION_AVAILABLE` to update the rest of the app.

2024-10-18 20:22 UTC, azfoo commented on tilia/timelines/hierarchy/timeline.py
> +        elif playback_time.end == 0 and (end > media_duration or start < 0):
Fair point. I think I left this over from before I made changes to how files were loaded.  It should be fine without that clause.

2024-10-18 20:40 UTC, azfoo commented on tilia/ui/timelines/collection/collection.py
> +        self.on_loop_change(self.selected_time, self.selected_time)
To avoid drawing a (empty) loop box beyond the playback time range, since playback_start could be more than 0.

2024-10-18 20:45 UTC, azfoo commented on tilia/ui/dialogs/scale_or_crop.py
> +        PROMPT = 2
The values are hard coded so I can check which of the radio buttons in the dialog have been selected. 
The Literals in the App class are all from the CLI that are also converted into Enums - will move the logic into the CLI. 
Will also separate the logic between the GUI and CLI.

2024-10-18 20:47 UTC, azfoo commented on tilia/ui/windows/metadata.py
> +            self.end_time.valueChanged.connect(lambda value: on_end_time_changed(value))
think its fine for now. am thinking of making a range slider  to replace this at some point (as mentioned previously)

2024-10-19 16:19 UTC, FelipeDefensor commented on tilia/app.py
> +            post(Post.FILE_MEDIA_DURATION_CHANGED, duration, start, end)
Ok, got it.

2024-10-19 16:21 UTC, FelipeDefensor commented on tilia/ui/windows/metadata.py
> +            self.end_time.valueChanged.connect(lambda value: on_end_time_changed(value))
Oh, yes, forgot about that. All good, then.

2024-10-23 12:11 UTC, FelipeDefensor requested changes
The changes are perfect :).

Few new bugs I found:
- Pre-start and post-end were not being scaled correctly. I fixed that with a commit.
- Something goes wrong shen scaling multiple segmentlikes. I added a test for that behavior.
- Undoing a media load with scale or crop triggers the dialog again. We could either reset the undo history when loading a new media or somehow store whether the user chose the scale or crop options.

We are almost there!

2025-02-22 15:28 UTC, closed without merging