Add 'open' and 'export' command to CLI
TimeLineAnnotator/desktop pull request #197
Opened 2024-10-13 12:00 UTC by FelipeDefensor

I know I said we should only fix bugs and improve user experience for v0.5, but I really needed these two commands for some work on my PhD.

2024-10-15 16:16 UTC, azfoo requested changes
seems to work fine. perhaps a check on the file extension on export to prevent silly mistakes?

2024-10-15 16:16 UTC, azfoo commented on tests/test_app.py
> +        assert settings.get_recent_files()[0] == tmp_file
needs to be `Path(settings.get_recent_files()[0])` to not fail on Windows

2024-10-15 16:16 UTC, azfoo commented on tests/test_app.py
> +        assert settings.get_recent_files()[0] == tmp_file
same here

2024-10-15 17:40 UTC, FelipeDefensor commented on tilia/timelines/base/component.py
That would also be handy to encapsulate things like doing maths with measures, which is not always trivial when dealing with changing time signatures. Will do!

2024-10-15 17:41 UTC, FelipeDefensor commented on tilia/timelines/base/component.py
> Nice abstraction! Think they could probably have more intuitive names. metric position, measure and beat could probably become some kind of data class, especially in the extended one, to include the lengths in it.

I agree the naming could be better. Any ideas?

2024-10-15 17:43 UTC, FelipeDefensor commented
So, I got carelles and forogot to initially push a large chunk of the work and then pushed all those WIP commits before squashing, sorry for that. You did review it only after I pushed the missing commits, right?

2024-10-15 19:03 UTC, azfoo commented
yes, the review was after the wips

2024-10-15 19:09 UTC, azfoo commented on tilia/timelines/base/component.py
maybe point/vertex and segment?

2024-10-15 22:26 UTC, azfoo commented on tilia/timelines/base/component.py
having -like in the name seems a little redundant. what do you think about dropping it?

2024-10-17 11:04 UTC, FelipeDefensor commented on tilia/timelines/base/component.py
In any case, I like "segment" as part of the name.

2024-10-17 12:51 UTC, azfoo approved these changes

2024-10-19 11:41 UTC, merged