Abstract component validation
TimeLineAnnotator/desktop pull request #208
Opened 2024-10-20 20:54 UTC by FelipeDefensor

Now that we have the `PointLikeTimelineComponent` and `SegmentLikeTimelineComponent`, this abstraction could be more easily located.

I also added some more validation to hierarchies. That should help spotting bugs earlier.

2024-10-21 19:24 UTC, azfoo requested changes
This could be further abstracted. Since each `_validate_component_creation` is composed of a `validate_<something>like_component_creation` and a `validate_unique_position_<something>like_component`, `_validate_component_creation` could be put into the parent class with each of the two child validates marked not initialised (to initialise in the child class).

i.e.`_validate_component_creation` goes into `TimelineComponentManager`, calls `component_kinds.validate_component_time` and `component_kinds.validate_unique_position`, so the two validators can be in the respective `TimelineComponent` classes (and probably renamed to `validate_component_time` and `validate_unique_position` or something similar)

2024-10-21 19:42 UTC, azfoo commented on tilia/timelines/base/component/base.py
> +    def user_friendly_name(self):
could do with a better name - this sounds like the original name is not readable. Maybe frontend_name or name_alt?

2024-10-21 20:03 UTC, FelipeDefensor commented on tilia/timelines/base/component/base.py
> +    def user_friendly_name(self):
Felt the same. I like frontend_name.

2024-10-21 20:11 UTC, FelipeDefensor commented
> This could be further abstracted. Since each `_validate_component_creation` is composed of a `validate_<something>like_component_creation` and a `validate_unique_position_<something>like_component`, `_validate_component_creation` could be put into the parent class with each of the two child validates marked not initialised (to initialise in the child class).
> 
> i.e.`_validate_component_creation` is moved into `TimelineComponentManager`, calls `self.component_kinds.validate_component_time` and `component_kinds.validate_unique_position`, so the two validators can be in the respective `TimelineComponent` classes (and probably renamed to `validate_component_time` and `validate_unique_position` or something similar)

Good point. Will do that.

2024-10-24 13:28 UTC, azfoo approved these changes

2024-10-24 13:40 UTC, merged