Make restoring state a lot faster
TimeLineAnnotator/desktop pull request #215
Opened 2024-10-24 14:50 UTC by FelipeDefensor

2024-10-28 22:27 UTC, azfoo requested changes

2024-11-04 12:35 UTC, FelipeDefensor commented
@azfoo review this one when you get a chance, please.

2024-11-04 13:59 UTC, azfoo requested changes

2024-11-04 13:59 UTC, azfoo commented on tests/ui/timelines/audiowave/test_audiowave_timeline_ui.py
> +    # as audiowave timeline has no undoable actions
maybe cache the old hash and compare to make sure nothing has changed instead? 
and perhaps something similar with the slider timeline's undo/redo

2024-12-13 22:30 UTC, azfoo approved these changes

2024-12-15 12:39 UTC, merged