Make it possible to create timeline with no media loaded
TimeLineAnnotator/desktop pull request #227
Opened 2024-11-05 14:59 UTC by FelipeDefensor

The user will now be asked whether to load a media file or to set the media duration manually when trying to create a timeline with no media loaded. This saves a few clicks in the former but, more importantly, it gives the option of annotating with no media loaded. This will be crucial if the user wants to work directly with a score in a score timeline.

I also refactored the `Get.FROM_USER_<SOMETHING>` responses to more consistenly return something of the form (success: bool, value: Any).

Closes #218.

2024-11-07 16:36 UTC, azfoo requested changes
hierarchy handles causes crash when dragged.

2024-11-07 17:16 UTC, azfoo commented
> hierarchy handles causes crash when dragged.

Actually, no. This seems to be a bug introduced before this.

2024-11-11 11:22 UTC, FelipeDefensor commented
I fixed the dragging in the dev branch. I merged it (instead of rebasing) to avoid having to force push.

2024-11-18 15:05 UTC, azfoo approved these changes

2024-11-18 17:56 UTC, merged