Some fixes and improvements to score timeline
TimeLineAnnotator/desktop pull request #239
Opened 2024-12-16 14:16 UTC by FelipeDefensor

The three main things:
- Moving SVGViewer to frontend
- Prompting for the creation of measure zero when importing
- Fix wrong barline position after importing

The specific commit messages go into more detail. This also has some other commits for other smaller useful things.

2024-12-17 14:21 UTC, azfoo reviewed
The reason for leaving it in the back end is CLI usability for saving SVG data. mxl data is converted to SVG data through an invisible web channel and saved from there. What could happen instead is separating the mxl-svg conversion from the display then separating front and backend from there. Will work on that.

2024-12-18 13:33 UTC, FelipeDefensor commented
> What could happen instead is separating the mxl-svg conversion from the display then separating front and backend from there. Will work on that.

If you did get a chance to review rest of this PR, we could merge this commit and make a new PR for those changes.

2024-12-18 19:29 UTC, azfoo requested changes

2024-12-18 19:29 UTC, azfoo commented on tilia/parsers/score/musicxml.py
> +    if tree.find('.//measure[@number="0"]') is not None and (0 not in beat_tl.measure_numbers):
this is too generalised a solution - if the user does not actually want to import the entire score, not having a measure 0 would prevent the entire process from happening.

perhaps a dialog that shows which beat_tl measures are available and the measure number range found in the score instead so the user can confirm which measures are needed?

I'm still not terribly keen on creating measure 0 for the user - part of having user input timestamps is that the beats of music are not necessarily even and predictable. Resetting measure numbers or actually inputting a measure 0 is not too many clicks away.

2024-12-18 19:29 UTC, azfoo commented on tilia/ui/timelines/score/timeline.py
> +        self.__svg_view = None
doesn't work - will cause view to disappear whenever any kind of action is done on it. but will fix after this PR.

2024-12-18 23:21 UTC, FelipeDefensor commented on tilia/parsers/score/musicxml.py
> +    if tree.find('.//measure[@number="0"]') is not None and (0 not in beat_tl.measure_numbers):
> this is too generalised a solution - if the user does not actually want to import the entire score, not having a measure 0 would prevent the entire process from happening.

That is a fair point, although I imagine importing the entire score will be by far the most common use case. Stopping the import if no measure 0 is found is to prevent the crash that would follow due to the lack of a clef in measure 1 for positioning the beats. What we could do instead is to "push" the clefs to measure 1 when there is no measure 0. What do you think? Even in that case, I think we should prompt for adding measure 0, as I think most users will expect the anacrusis to be magically imported.

> perhaps a dialog that shows which beat_tl measures are available and the measure number range found in the score instead so the user can confirm which measures are needed?

This would be an extra step for all users to cover only a niche use case, namely, the user has beats for the whole media but only wants to import part of the score. If the user only wants the score for a portion of the media, then I would expect that they only create beats for that portion. In that case, "pushing" the clefs to the first imported beat would prevent crashes.

> I'm still not terribly keen on creating measure 0 for the user - part of having user input timestamps is that the beats of music are not necessarily even and predictable. Resetting measure numbers or actually inputting a measure 0 is not too many clicks away.

I think most users won't realize the anacrusis are missing beacuse there is no measure 0, they will simply think something is wrong with the import. I, for one, never realized anacrusis measure had a number in score editors until recently. I though of them as a special unumbered case. If the user wants to have precise timestamps for measure 0, then they can create it manually, that is also only a few clicks away, but I rather we add that extra step for what I think will be the minority of users. Maybe we disagree with what will be the standard use case and to which extent it will be standard.

2024-12-18 23:22 UTC, FelipeDefensor commented on tilia/ui/timelines/score/timeline.py
> +        self.__svg_view = None
Maybe that explains #246?

2024-12-19 11:28 UTC, azfoo commented on tilia/ui/timelines/score/timeline.py
> +        self.__svg_view = None
yes. I've been working on a fix for that but will push after this one has been merged

2024-12-19 11:35 UTC, azfoo commented on tilia/parsers/score/musicxml.py
> +    if tree.find('.//measure[@number="0"]') is not None and (0 not in beat_tl.measure_numbers):
"Pushing" clefs would be a necessary thing whenever an incomplete score is imported. Will add that on to the score-parser branch.

Still, implementing a forced measure 0 this way would seem to be a weird bug if the user does not import any measure close by. Expanding this solution for an anacrusis that happens in the middle of the score (which would not be numbered 0) would be a logical next step, but detecting the existence of anacruses might fall outside the scope of this project.

2024-12-19 11:44 UTC, FelipeDefensor commented on tilia/parsers/score/musicxml.py
> +    if tree.find('.//measure[@number="0"]') is not None and (0 not in beat_tl.measure_numbers):
> "Pushing" clefs would be a necessary thing whenever an incomplete score is imported. Will add that on to the score-parser branch.

What about we merge this and you make a new PR? That way avoid a potentailly large rebase of another branch.

> Still, implementing a forced measure 0 this way would seem to be a weird bug if the user does not import any measure close by.

Nice catch. To get arount that we could prompt for measure 0 only if measure 1 is being imported.

> Expanding this solution for an anacrusis that happens in the middle of the score (which would not be numbered 0) would be a logical next step, but detecting the existence of anacruses might fall outside the scope of this project.

Agreed. There's no easy way to detect an anacrusis in the middle of the score.

2024-12-19 15:01 UTC, azfoo commented on tilia/parsers/score/musicxml.py
> +    if tree.find('.//measure[@number="0"]') is not None and (0 not in beat_tl.measure_numbers):
right. could you implement the check for measure 0/1, then we merge and I'll start work.

2024-12-19 17:22 UTC, FelipeDefensor commented on tilia/parsers/score/musicxml.py
> +    if tree.find('.//measure[@number="0"]') is not None and (0 not in beat_tl.measure_numbers):
Done. Will merge.

2024-12-19 17:26 UTC, merged